const router = require('express').Router();
const jwt = require('jsonwebtoken');
const { body, validationResult } = require('express-validator');
const User = require('../models/User');
const auth = require('../middleware/auth');
const strongPassword = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/;
const validate = (req,res,next) => { const errors=validationResult(req); return errors.isEmpty()?next():res.status(422).json({errors:errors.array()}); };
router.post('/register', [body('name').trim().isLength({min:2,max:80}), body('email').isEmail().normalizeEmail(), body('password').matches(strongPassword).withMessage('Password must be at least 8 characters and include uppercase, lowercase, number, and symbol.')], validate, async(req,res,next)=>{ try { if(await User.exists({email:req.body.email})) return res.status(409).json({message:'Email already registered'}); const user=await User.create(req.body); res.status(201).json({id:user.id,name:user.name,email:user.email}); } catch(e){next(e);} });
router.post('/login', [body('email').isEmail().normalizeEmail(), body('password').notEmpty()], validate, async(req,res,next)=>{ try { const user=await User.findOne({email:req.body.email}); if(!user || !await user.comparePassword(req.body.password)) return res.status(401).json({message:'Invalid credentials'}); const token=jwt.sign({id:user.id,role:user.role},process.env.JWT_SECRET,{expiresIn:'8h'}); res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e);} });
router.get('/profile',auth,async(req,res,next)=>{try{const user=await User.findById(req.user.id).select('-password');if(!user)return res.status(404).json({message:'User not found'});res.json(user);}catch(e){next(e);}});
router.put('/profile',auth,[body('name').trim().isLength({min:2,max:80})],validate,async(req,res,next)=>{try{const user=await User.findByIdAndUpdate(req.user.id,{name:req.body.name},{new:true,runValidators:true}).select('-password');if(!user)return res.status(404).json({message:'User not found'});res.json({id:user.id,name:user.name,email:user.email,role:user.role});}catch(e){next(e);}});
module.exports = router;
