const router = require('express').Router();
const auth = require('../middleware/auth');
const User = require('../models/User');
const Patient = require('../models/Patient');
const Appointment = require('../models/Appointment');
const Encounter = require('../models/Encounter');
const Prescription = require('../models/Prescription');
const Referral = require('../models/Referral');
const Notification = require('../models/Notification');
router.use(auth);
const actor = req => User.findById(req.user.id).select('name role');
const dayRange = value => { const start = value ? new Date(value) : new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { start, end }; };
const populateEncounter = query => query.populate('patient', 'firstName lastName email phone birthDate sex address').populate('doctor', 'name specialty').populate('appointment');

router.get('/queue', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','receptionist','doctor','nurse'].includes(user.role)) return res.status(403).json({ message: 'Queue access denied' }); const { start, end } = dayRange(req.query.date); const filter = { queueDate: { $gte: start, $lt: end }, ...(user.role === 'doctor' ? { doctor: user._id } : {}) }; res.json(await populateEncounter(Encounter.find(filter).sort({ queueNumber: 1 }))); } catch (e) { next(e); } });

router.post('/check-in/:appointmentId', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','receptionist'].includes(user.role)) return res.status(403).json({ message: 'Reception access required' }); const appointment = await Appointment.findById(req.params.appointmentId); if (!appointment) return res.status(404).json({ message: 'Appointment not found' }); if (await Encounter.exists({ appointment: appointment._id })) return res.status(409).json({ message: 'Patient is already checked in' }); const doctor = await User.findOne({ name: appointment.doctor, role: 'doctor' }); if (!doctor) return res.status(422).json({ message: 'Assigned doctor account not found' }); const names = appointment.patient.trim().split(/\s+/); const identity = appointment.email ? { email: appointment.email } : { phone: appointment.phone }; let patient = await Patient.findOne(identity); if (!patient) patient = await Patient.create({ firstName: names.shift(), lastName: names.join(' ') || 'Patient', email: appointment.email, phone: appointment.phone || 'Not provided', birthDate: appointment.birthDate || new Date('1900-01-01'), sex: appointment.sex || 'Other', address: appointment.address, assignedDoctors: [doctor._id], createdBy: req.user.id }); else if (!patient.assignedDoctors.some(id => id.equals(doctor._id))) { patient.assignedDoctors.push(doctor._id); await patient.save(); } const { start, end } = dayRange(); const queueNumber = await Encounter.countDocuments({ queueDate: { $gte: start, $lt: end } }) + 1; const encounter = await Encounter.create({ appointment: appointment._id, patient: patient._id, doctor: doctor._id, queueNumber, queueDate: new Date(), checkedInBy: req.user.id }); await Notification.create({ user: doctor._id, type: 'Appointment', title: `Queue #${queueNumber} checked in`, message: `${appointment.patient} is waiting for consultation.`, link: '/queue' }); res.status(201).json(await populateEncounter(Encounter.findById(encounter._id))); } catch (e) { next(e); } });

router.patch('/queue/:id/status', async (req, res, next) => { try { const user = await actor(req); const item = await Encounter.findById(req.params.id); if (!item) return res.status(404).json({ message: 'Queue entry not found' }); const transitions = { Waiting: ['In consultation','No-show'], 'In consultation': ['Completed'], Completed: [], 'No-show': [] }; if (!transitions[item.status].includes(req.body.status)) return res.status(422).json({ message: 'Invalid queue status transition' }); if (req.body.status === 'No-show' && !['superadmin','admin','receptionist','doctor'].includes(user.role)) return res.status(403).json({ message: 'Access denied' }); if (req.body.status !== 'No-show' && user.role !== 'doctor') return res.status(403).json({ message: 'Only the assigned doctor can progress consultation' }); if (user.role === 'doctor' && !item.doctor.equals(user._id)) return res.status(403).json({ message: 'This patient is assigned to another doctor' }); item.status = req.body.status; await item.save(); res.json(item); } catch (e) { next(e); } });

router.put('/queue/:id/vitals', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','nurse'].includes(user.role)) return res.status(403).json({ message: 'Nursing access required' }); const item = await Encounter.findByIdAndUpdate(req.params.id, { vitals: { ...req.body, recordedBy: req.user.id, recordedAt: new Date() } }, { new: true, runValidators: true }); if (!item) return res.status(404).json({ message: 'Encounter not found' }); res.json(item); } catch (e) { next(e); } });

router.put('/queue/:id/follow-up', async (req, res, next) => { try { const user = await actor(req); if (user.role !== 'doctor') return res.status(403).json({ message: 'Doctor access required' }); const item = await Encounter.findOneAndUpdate({ _id: req.params.id, doctor: user._id }, { followUpDate: req.body.followUpDate, followUpNotes: req.body.followUpNotes }, { new: true }); if (!item) return res.status(404).json({ message: 'Encounter not found' }); await Notification.create({ roles: ['receptionist','admin','superadmin'], type: 'Follow-up', title: 'Follow-up scheduling requested', message: `A follow-up was recommended for ${new Date(req.body.followUpDate).toLocaleDateString()}.`, link: '/queue' }); res.json(item); } catch (e) { next(e); } });
router.post('/follow-ups/:id/schedule', async(req,res,next)=>{try{const user=await actor(req);if(!['superadmin','admin','receptionist'].includes(user.role))return res.status(403).json({message:'Reception access required'});const encounter=await Encounter.findById(req.params.id).populate('patient').populate('doctor');if(!encounter?.followUpDate)return res.status(422).json({message:'No follow-up recommendation found'});if(await Appointment.exists({followUpOf:encounter._id}))return res.status(409).json({message:'Follow-up already scheduled'});const p=encounter.patient;const appointment=await Appointment.create({patient:`${p.firstName} ${p.lastName}`,email:p.email,phone:p.phone,birthDate:p.birthDate,sex:p.sex,address:p.address,reason:encounter.followUpNotes||'Follow-up consultation',doctor:encounter.doctor.name,date:req.body.date||encounter.followUpDate,status:'Pending',followUpOf:encounter._id,createdBy:req.user.id});res.status(201).json(appointment)}catch(e){next(e)}});

router.get('/prescriptions', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','doctor','nurse'].includes(user.role)) return res.status(403).json({ message: 'Clinical access required' }); const filter = user.role === 'doctor' ? { doctor: user._id } : {}; res.json(await Prescription.find(filter).populate('patient', 'firstName lastName birthDate sex address').populate('doctor', 'name specialty').populate('encounter').sort({ issuedAt: -1 })); } catch (e) { next(e); } });
router.post('/prescriptions', async (req, res, next) => { try { const user = await actor(req); if (user.role !== 'doctor') return res.status(403).json({ message: 'Doctor access required' }); const encounter = await Encounter.findOne({ _id: req.body.encounter, doctor: user._id, status: 'Completed' }); if (!encounter) return res.status(422).json({ message: 'Prescriptions require your completed consultation' }); res.status(201).json(await Prescription.create({ encounter: encounter._id, patient: encounter.patient, doctor: user._id, medicines: req.body.medicines })); } catch (e) { next(e); } });

router.get('/referrals', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','doctor','nurse','receptionist'].includes(user.role)) return res.status(403).json({ message: 'Referral access denied' }); const filter = user.role === 'doctor' ? { referringDoctor: user._id } : {}; res.json(await Referral.find(filter).populate('patient', 'firstName lastName phone').populate('referringDoctor', 'name specialty').sort({ createdAt: -1 })); } catch (e) { next(e); } });
router.post('/referrals', async (req, res, next) => { try { const user = await actor(req); if (user.role !== 'doctor') return res.status(403).json({ message: 'Doctor access required' }); res.status(201).json(await Referral.create({ ...req.body, referringDoctor: user._id })); } catch (e) { next(e); } });
router.patch('/referrals/:id/status', async (req, res, next) => { try { const user = await actor(req); if (!['superadmin','admin','doctor','receptionist'].includes(user.role)) return res.status(403).json({ message: 'Referral access denied' }); const item = await Referral.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true, runValidators: true }); if (!item) return res.status(404).json({ message: 'Referral not found' }); res.json(item); } catch (e) { next(e); } });
module.exports = router;
