import { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { ChevronLeft, ChevronRight, DollarSign, Eye, FlaskConical, Pencil, Trash2, X } from 'lucide-react';
import api from './api';
import { useAuth } from './AuthContext';

const configs = {
  billing: { title: 'Billing', icon: <DollarSign />, blank: { patient: '', description: '', amount: '', dueDate: '', status: 'Unpaid' }, writeRoles: ['superadmin', 'admin', 'billing'] },
  laboratory: { title: 'Laboratory', icon: <FlaskConical />, blank: { patient: '', doctor: '', testName: '', requestedDate: '', status: 'Requested', result: '', notes: '' }, writeRoles: ['superadmin', 'admin', 'laboratory'] },
};
export function BillingPage() { return <OperationsPage type="billing" />; }
export function LaboratoryPage() { return <OperationsPage type="laboratory" />; }

function OperationsPage({ type }) {
  const { user } = useAuth(), config = configs[type], canWrite = config.writeRoles.includes(user.role);
  const [items, setItems] = useState([]), [page, setPage] = useState(1), [pages, setPages] = useState(1), [total, setTotal] = useState(0), [q, setQ] = useState(''), [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [viewing, setViewing] = useState(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { const { data } = await api.get(`/${type}`, { params: { page, limit: 8, q } }); setItems(data.data); setPages(data.pages); setTotal(data.total); setError(''); } catch (e) { setError(e.response?.data?.message || `Unable to load ${config.title.toLowerCase()} records.`); } }, [type, config.title, page, q]);
  useEffect(() => { load(); }, [load]);
  const save = async form => { editing ? await api.put(`/${type}/${editing._id}`, form) : await api.post(`/${type}`, form); setOpen(false); setEditing(null); load(); };
  const remove = async id => { if (window.confirm('Delete this record?')) { await api.delete(`/${type}/${id}`); load(); } };
  return <div className="page operations-page"><section className="subhero"><div className="eyebrow"><span>{type === 'billing' ? '07' : '08'}</span> Clinic operations</div><h1>{config.title},<br/><em>organized.</em></h1>{canWrite && <button className="primary" onClick={() => { setEditing(null); setOpen(true); }}>Add record ↗</button>}</section><div className="module-search"><input value={q} onChange={e => { setQ(e.target.value); setPage(1); }} placeholder={`Search ${config.title.toLowerCase()}...`}/><span>{total} records</span></div>{error && <div className="form-error api-error">{error}</div>}<div className="data-table">{items.length ? items.map(item => <div className="data-row operations-row" key={item._id}><div className="data-icon">{config.icon}</div><div><b>{item.patient ? `${item.patient.firstName} ${item.patient.lastName}` : 'Deleted patient'}</b><span>{type === 'billing' ? item.description : item.testName}</span></div><div><small>{type === 'billing' ? 'Amount' : 'Requested by'}</small><span>{type === 'billing' ? `₱${Number(item.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}` : (item.doctor?.name || 'Clinic')}</span></div><div><small>Status</small><span className={`status ${item.status.toLowerCase().replaceAll(' ', '-')}`}>{item.status}</span></div><div className="row-actions detail-actions"><button className="view-details" onClick={() => setViewing(item)}><Eye/><span>View</span></button>{canWrite && <><button onClick={() => { setEditing(item); setOpen(true); }}><Pencil/></button><button onClick={() => remove(item._id)}><Trash2/></button></>}</div></div>) : <div className="empty">No {config.title.toLowerCase()} records found.</div>}<div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft/> Previous</button><span>Page {page} of {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)}>Next <ChevronRight/></button></div></div>{open && <OperationModal type={type} item={editing} config={config} onClose={() => setOpen(false)} onSave={save}/>} {viewing && <OperationDetails type={type} item={viewing} onClose={() => setViewing(null)}/>}</div>;
}

function OperationModal({ type, item, config, onClose, onSave }) {
  const normalize = () => !item ? config.blank : type === 'billing' ? { patient: item.patient?._id || '', description: item.description, amount: item.amount, dueDate: new Date(item.dueDate).toISOString().slice(0, 10), status: item.status } : { patient: item.patient?._id || '', doctor: item.doctor?._id || '', testName: item.testName, requestedDate: new Date(item.requestedDate).toISOString().slice(0, 10), status: item.status, result: item.result || '', notes: item.notes || '' };
  const [form, setForm] = useState(normalize), [patients, setPatients] = useState([]), [doctors, setDoctors] = useState([]), [error, setError] = useState('');
  useEffect(() => {
    const requests = [api.get('/patients', { params: { limit: 50 } })];
    if (type === 'laboratory') requests.push(api.get('/doctors'));
    Promise.all(requests).then(([p, d]) => {
      setPatients(p.data.data);
      setDoctors(d?.data || []);
    }).catch(() => setError('Unable to load the form options.'));
  }, [type]);
  const submit = async e => { e.preventDefault(); try { await onSave(form); } catch (e) { setError(e.response?.data?.message || e.response?.data?.errors?.[0]?.msg || 'Unable to save record.'); } };
  return createPortal(<div className="modal-backdrop"><form className="modal operation-modal" onSubmit={submit}><button type="button" className="modal-x" onClick={onClose}><X/></button><div className="eyebrow">{item ? 'Update' : 'Create'} operational record</div><h2>{item ? 'Edit' : 'Add'} {config.title}</h2><label>Patient<select value={form.patient} onChange={e => setForm({ ...form, patient: e.target.value })} required><option value="">Select patient</option>{patients.map(p => <option key={p._id} value={p._id}>{p.firstName} {p.lastName}</option>)}</select></label>{type === 'billing' ? <><label>Description<input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} required/></label><div className="form-row"><label>Amount (PHP)<input type="number" min="0" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} required/></label><label>Due date<input type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} required/></label></div><label>Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}>{['Unpaid', 'Paid', 'Void'].map(s => <option key={s}>{s}</option>)}</select></label></> : <><label>Requesting doctor<select value={form.doctor} onChange={e => setForm({ ...form, doctor: e.target.value })}><option value="">Clinic request</option>{doctors.map(d => <option key={d._id} value={d._id}>{d.name} — {d.specialty}</option>)}</select></label><label>Test name<input value={form.testName} onChange={e => setForm({ ...form, testName: e.target.value })} required/></label><div className="form-row"><label>Requested date<input type="date" value={form.requestedDate} onChange={e => setForm({ ...form, requestedDate: e.target.value })} required/></label><label>Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}>{['Requested', 'In Progress', 'Completed', 'Cancelled'].map(s => <option key={s}>{s}</option>)}</select></label></div><label>Result<textarea value={form.result} onChange={e => setForm({ ...form, result: e.target.value })}/></label><label>Notes<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label></>}{error && <div className="form-error">{error}</div>}<button className="primary full">Save record</button></form></div>, document.body);
}
function OperationDetails({ type, item, onClose }) { const value = v => v || '—'; return createPortal(<div className="modal-backdrop details-backdrop"><article className="modal details-modal"><button className="modal-x" onClick={onClose}><X/></button><div className="eyebrow">Read-only operational record</div><h2>{type === 'billing' ? 'Invoice details' : 'Laboratory details'}</h2><dl className="details-grid"><div><dt>Patient</dt><dd>{item.patient ? `${item.patient.firstName} ${item.patient.lastName}` : 'Deleted patient'}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div>{type === 'billing' ? <><div><dt>Amount</dt><dd>₱{Number(item.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}</dd></div><div><dt>Due date</dt><dd>{new Date(item.dueDate).toLocaleDateString()}</dd></div><div className="details-wide"><dt>Description</dt><dd>{value(item.description)}</dd></div><div><dt>Payment date</dt><dd>{item.paymentDate ? new Date(item.paymentDate).toLocaleDateString() : '—'}</dd></div></> : <><div><dt>Requested date</dt><dd>{new Date(item.requestedDate).toLocaleDateString()}</dd></div><div><dt>Requesting doctor</dt><dd>{value(item.doctor?.name)}</dd></div><div className="details-wide"><dt>Test</dt><dd>{value(item.testName)}</dd></div><div className="details-wide"><dt>Result</dt><dd>{value(item.result)}</dd></div><div className="details-wide"><dt>Notes</dt><dd>{value(item.notes)}</dd></div></>}</dl><button className="primary full" onClick={onClose}>Close details</button></article></div>, document.body); }
