import { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Bell, Boxes, ClipboardCheck, HeartPulse, Printer, RefreshCw, Stethoscope, Users, X } from 'lucide-react';
import api from './api';
import { useAuth } from './AuthContext';

const name = patient => patient ? `${patient.firstName} ${patient.lastName}` : 'Patient';
const date = value => value ? new Date(value).toLocaleString() : '—';
const roleIn = (user, roles) => roles.includes(user.role);
const PageHead = ({ number, label, title, italic, action }) => <section className="subhero workflow-hero"><div className="eyebrow"><span>{number}</span>{label}</div><h1>{title},<br/><em>{italic}.</em></h1>{action}</section>;
const Modal = ({ title, onClose, children }) => createPortal(<div className="modal-backdrop"><div className="modal workflow-modal"><button className="modal-x" onClick={onClose}><X/></button><div className="eyebrow">ClaraCare workflow</div><h2>{title}</h2>{children}</div></div>, document.body);

export function QueuePage() {
  const { user } = useAuth(), canCheckIn = roleIn(user,['superadmin','admin','receptionist']), nurse = roleIn(user,['superadmin','admin','nurse']), doctor=user.role==='doctor';
  const [queue,setQueue]=useState([]),[appointments,setAppointments]=useState([]),[vitals,setVitals]=useState(null),[error,setError]=useState('');
  const load=useCallback(async()=>{try{const calls=[api.get('/workflows/queue')];if(canCheckIn)calls.push(api.get('/appointments',{params:{limit:50}}));const [q,a]=await Promise.all(calls);setQueue(q.data);setAppointments(a?.data?.data||[]);setError('');}catch(e){setError(e.response?.data?.message||'Unable to load the live queue.');}},[canCheckIn]);
  useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[load]);
  const checkIn=async id=>{try{await api.post(`/workflows/check-in/${id}`);load()}catch(e){setError(e.response?.data?.message||'Unable to check in patient.')}};
  const status=async(id,value)=>{try{await api.patch(`/workflows/queue/${id}/status`,{status:value});load()}catch(e){setError(e.response?.data?.message||'Unable to update queue status.')}};
  const followUp=async item=>{const followUpDate=window.prompt('Recommended follow-up date (YYYY-MM-DD):');if(!followUpDate)return;const followUpNotes=window.prompt('Follow-up reason or instructions:')||'';await api.put(`/workflows/queue/${item._id}/follow-up`,{followUpDate,followUpNotes});load()};
  const schedule=async item=>{try{await api.post(`/workflows/follow-ups/${item._id}/schedule`,{});window.alert('Follow-up appointment scheduled.')}catch(e){setError(e.response?.data?.message||'Unable to schedule follow-up.')}};
  const queuedIds=new Set(queue.map(q=>q.appointment?._id));
  return <div className="page"><PageHead number="07" label="Live patient flow" title="Clinic queue" italic="moving" action={<button className="secondary icon-button" onClick={load}><RefreshCw/> Refresh</button>}/>{error&&<div className="form-error api-error">{error}</div>}
    {canCheckIn&&<section className="workflow-section"><div className="section-title"><div><div className="eyebrow">Reception desk</div><h3>Expected appointments</h3></div></div><div className="compact-cards">{appointments.filter(a=>!queuedIds.has(a._id)&&!['Completed','Cancelled'].includes(a.status)).map(a=><article key={a._id}><div><b>{a.patient}</b><span>{date(a.date)} · {a.doctor}</span></div><button className="primary compact" onClick={()=>checkIn(a._id)}>Check in</button></article>)}{!appointments.filter(a=>!queuedIds.has(a._id)&&!['Completed','Cancelled'].includes(a.status)).length&&<div className="empty">No appointments awaiting check-in.</div>}</div></section>}
    <section className="workflow-section"><div className="section-title"><div><div className="eyebrow">Today</div><h3>Live queue</h3></div><span>{queue.length} patients</span></div><div className="queue-grid">{queue.map(item=><article className={`queue-card queue-${item.status.toLowerCase().replaceAll(' ','-')}`} key={item._id}><div className="queue-number">{String(item.queueNumber).padStart(2,'0')}</div><div><h3>{name(item.patient)}</h3><p>{item.appointment?.reason} · Dr. {item.doctor?.name}</p><span className="status">{item.status}</span>{item.vitals?.recordedAt&&<small>Vitals recorded · BP {item.vitals.bloodPressure||'—'} · SpO₂ {item.vitals.oxygenLevel||'—'}%</small>}{item.followUpDate&&<small>Follow-up: {new Date(item.followUpDate).toLocaleDateString()}</small>}</div><div className="queue-actions">{nurse&&item.status==='Waiting'&&<button onClick={()=>setVitals(item)}><HeartPulse/> Vitals</button>}{doctor&&item.status==='Waiting'&&<button onClick={()=>status(item._id,'In consultation')}><Stethoscope/> Start</button>}{doctor&&item.status==='In consultation'&&<button onClick={()=>status(item._id,'Completed')}><ClipboardCheck/> Complete</button>}{(doctor||canCheckIn)&&item.status==='Waiting'&&<button onClick={()=>status(item._id,'No-show')}>No-show</button>}{doctor&&item.status==='Completed'&&<button onClick={()=>followUp(item)}>Recommend follow-up</button>}{canCheckIn&&item.followUpDate&&<button onClick={()=>schedule(item)}>Schedule follow-up</button>}</div></article>)}{!queue.length&&<div className="empty">The live queue is empty.</div>}</div></section>
    {vitals&&<VitalsModal item={vitals} onClose={()=>setVitals(null)} onSaved={()=>{setVitals(null);load()}}/>}
  </div>;
}
function VitalsModal({item,onClose,onSaved}){const [form,setForm]=useState({temperature:'',bloodPressure:'',pulse:'',weight:'',height:'',oxygenLevel:'',allergies:'',initialComplaint:''}),[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{await api.put(`/workflows/queue/${item._id}/vitals`,form);onSaved()}catch(e){setError(e.response?.data?.message||'Unable to save assessment.')}};return <Modal title={`Nursing assessment — ${name(item.patient)}`} onClose={onClose}><form onSubmit={submit}><div className="form-row"><label>Temperature °C<input type="number" step="0.1" value={form.temperature} onChange={e=>setForm({...form,temperature:e.target.value})}/></label><label>Blood pressure<input placeholder="120/80" value={form.bloodPressure} onChange={e=>setForm({...form,bloodPressure:e.target.value})}/></label></div><div className="form-row"><label>Pulse (bpm)<input type="number" value={form.pulse} onChange={e=>setForm({...form,pulse:e.target.value})}/></label><label>Oxygen level (%)<input type="number" value={form.oxygenLevel} onChange={e=>setForm({...form,oxygenLevel:e.target.value})}/></label></div><div className="form-row"><label>Weight (kg)<input type="number" step="0.1" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><label>Height (cm)<input type="number" step="0.1" value={form.height} onChange={e=>setForm({...form,height:e.target.value})}/></label></div><label>Known allergies<textarea value={form.allergies} onChange={e=>setForm({...form,allergies:e.target.value})}/></label><label>Initial complaint<textarea value={form.initialComplaint} onChange={e=>setForm({...form,initialComplaint:e.target.value})} required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary full">Save nursing assessment</button></form></Modal>}

export function PrescriptionsPage(){const{user}=useAuth(),[items,setItems]=useState([]),[queue,setQueue]=useState([]),[open,setOpen]=useState(false);const load=useCallback(()=>Promise.all([api.get('/workflows/prescriptions'),api.get('/workflows/queue')]).then(([p,q])=>{setItems(p.data);setQueue(q.data.filter(x=>x.status==='Completed'))}),[]);useEffect(()=>{load()},[load]);return <div className="page"><PageHead number="08" label="Medication management" title="Prescriptions" italic="documented" action={user.role==='doctor'&&<button className="primary" onClick={()=>setOpen(true)}>Create prescription ↗</button>}/><div className="document-list">{items.map(p=><article className="printable-card" key={p._id}><div className="clinic-document-head"><HeartPulse/><div><b>CLARA care</b><span>Official Prescription</span></div><button className="print-hide" onClick={()=>window.print()}><Printer/> Print</button></div><h3>{name(p.patient)}</h3><p>Dr. {p.doctor?.name} · {new Date(p.issuedAt).toLocaleDateString()}</p>{p.medicines.map((m,i)=><div className="medicine-line" key={i}><b>Rx {m.medicine}</b><span>{m.dosage} · {m.frequency} · {m.duration}</span><small>{m.instructions}</small></div>)}<div className="signature-line">Dr. {p.doctor?.name}<small>Authorized physician</small></div></article>)}{!items.length&&<div className="empty">No prescriptions yet.</div>}</div>{open&&<PrescriptionModal encounters={queue} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</div>}
function PrescriptionModal({encounters,onClose,onSaved}){const [encounter,setEncounter]=useState(''),[medicines,setMedicines]=useState([{medicine:'',dosage:'',frequency:'',duration:'',instructions:''}]),[error,setError]=useState('');const update=(i,key,value)=>setMedicines(medicines.map((m,n)=>n===i?{...m,[key]:value}:m));const submit=async e=>{e.preventDefault();try{await api.post('/workflows/prescriptions',{encounter,medicines});onSaved()}catch(e){setError(e.response?.data?.message||'Unable to create prescription.')}};return <Modal title="Create prescription" onClose={onClose}><form onSubmit={submit}><label>Completed consultation<select value={encounter} onChange={e=>setEncounter(e.target.value)} required><option value="">Select patient</option>{encounters.map(x=><option key={x._id} value={x._id}>{name(x.patient)} — Queue {x.queueNumber}</option>)}</select></label>{medicines.map((m,i)=><div className="repeat-form" key={i}><label>Medicine<input value={m.medicine} onChange={e=>update(i,'medicine',e.target.value)} required/></label><div className="form-row"><label>Dosage<input value={m.dosage} onChange={e=>update(i,'dosage',e.target.value)} required/></label><label>Frequency<input value={m.frequency} onChange={e=>update(i,'frequency',e.target.value)} required/></label></div><div className="form-row"><label>Duration<input value={m.duration} onChange={e=>update(i,'duration',e.target.value)} required/></label><label>Instructions<input value={m.instructions} onChange={e=>update(i,'instructions',e.target.value)}/></label></div></div>)}<button type="button" className="secondary" onClick={()=>setMedicines([...medicines,{medicine:'',dosage:'',frequency:'',duration:'',instructions:''}])}>Add medicine</button>{error&&<div className="form-error">{error}</div>}<button className="primary full">Issue prescription</button></form></Modal>}

export function ReferralsPage(){const{user}=useAuth(),[items,setItems]=useState([]),[patients,setPatients]=useState([]),[open,setOpen]=useState(false);const load=useCallback(()=>Promise.all([api.get('/workflows/referrals'),api.get('/patients',{params:{limit:50}})]).then(([r,p])=>{setItems(r.data);setPatients(p.data.data)}),[]);useEffect(()=>{load()},[load]);return <div className="page"><PageHead number="09" label="Coordinated care" title="Patient referrals" italic="connected" action={user.role==='doctor'&&<button className="primary" onClick={()=>setOpen(true)}>Create referral ↗</button>}/><div className="document-list">{items.map(r=><article className="printable-card" key={r._id}><div className="clinic-document-head"><Users/><div><b>CLARA care</b><span>{r.referralType} referral</span></div><button className="print-hide" onClick={()=>window.print()}><Printer/> Print</button></div><h3>{name(r.patient)}</h3><p>Referred to <b>{r.destination}</b></p><p>{r.reason}</p><span className="status">{r.status}</span><div className="signature-line">Dr. {r.referringDoctor?.name}<small>{r.referringDoctor?.specialty}</small></div></article>)}{!items.length&&<div className="empty">No referrals recorded.</div>}</div>{open&&<ReferralModal patients={patients} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</div>}
function ReferralModal({patients,onClose,onSaved}){const[form,setForm]=useState({patient:'',destination:'',referralType:'Specialist',reason:''}),[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{await api.post('/workflows/referrals',form);onSaved()}catch(e){setError(e.response?.data?.message||'Unable to create referral.')}};return <Modal title="Create patient referral" onClose={onClose}><form onSubmit={submit}><label>Patient<select value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})} required><option value="">Select patient</option>{patients.map(p=><option key={p._id} value={p._id}>{name(p)}</option>)}</select></label><label>Referral type<select value={form.referralType} onChange={e=>setForm({...form,referralType:e.target.value})}>{['Doctor','Specialist','Hospital','Laboratory'].map(v=><option key={v}>{v}</option>)}</select></label><label>Destination<input value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} required/></label><label>Reason<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary full">Create referral</button></form></Modal>}

export function InventoryPage(){const[items,setItems]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState('');const load=useCallback(()=>api.get('/inventory').then(r=>setItems(r.data)).catch(e=>setError(e.response?.data?.message||'Unable to load inventory.')),[]);useEffect(()=>{load()},[load]);const movement=async(item,type)=>{const quantity=window.prompt(`${type} quantity:`);if(!quantity)return;await api.post(`/inventory/${item._id}/movements`,{type,quantity:Number(quantity)});load()};return <div className="page"><PageHead number="10" label="Supplies and medicines" title="Clinic inventory" italic="accounted" action={<button className="primary" onClick={()=>setOpen(true)}>Add item ↗</button>}/>{error&&<div className="form-error api-error">{error}</div>}<div className="inventory-grid">{items.map(item=>{const low=item.quantity<=item.reorderLevel,expiring=item.expiryDate&&new Date(item.expiryDate)<new Date(Date.now()+30*86400000);return <article key={item._id} className={low||expiring?'inventory-alert':''}><Boxes/><div><small>{item.category} · {item.sku}</small><h3>{item.name}</h3><strong>{item.quantity} {item.unit}</strong>{low&&<span>Low stock</span>}{expiring&&<span>Expiring {new Date(item.expiryDate).toLocaleDateString()}</span>}</div><div><button onClick={()=>movement(item,'Received')}>Receive</button><button onClick={()=>movement(item,'Used')}>Use</button></div></article>})}{!items.length&&<div className="empty">No inventory items yet.</div>}</div>{open&&<InventoryModal onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</div>}
function InventoryModal({onClose,onSaved}){const[form,setForm]=useState({name:'',category:'Medicine',sku:'',quantity:0,unit:'pieces',reorderLevel:5,expiryDate:''}),[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{await api.post('/inventory',form);onSaved()}catch(e){setError(e.response?.data?.message||'Unable to save inventory item.')}};return <Modal title="Add inventory item" onClose={onClose}><form onSubmit={submit}><label>Item name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><div className="form-row"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Medicine','Laboratory','Medical supply'].map(v=><option key={v}>{v}</option>)}</select></label><label>SKU<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} required/></label></div><div className="form-row"><label>Opening quantity<input type="number" min="0" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} required/></label></div><div className="form-row"><label>Low-stock level<input type="number" min="0" value={form.reorderLevel} onChange={e=>setForm({...form,reorderLevel:e.target.value})}/></label><label>Expiry date<input type="date" value={form.expiryDate} onChange={e=>setForm({...form,expiryDate:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<button className="primary full">Add inventory item</button></form></Modal>}

export function DocumentsPage(){const[queue,setQueue]=useState([]),[selected,setSelected]=useState(''),[type,setType]=useState('Medical Certificate');useEffect(()=>{api.get('/workflows/queue').then(r=>setQueue(r.data.filter(x=>x.status==='Completed')))},[]);const item=queue.find(x=>x._id===selected);return <div className="page"><PageHead number="11" label="Official clinic documents" title="Documents" italic="ready to print"/><section className="document-builder print-hide"><label>Document type<select value={type} onChange={e=>setType(e.target.value)}>{['Medical Certificate','Consultation Summary','Laboratory Request'].map(v=><option key={v}>{v}</option>)}</select></label><label>Completed encounter<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select patient</option>{queue.map(x=><option key={x._id} value={x._id}>{name(x.patient)} — {date(x.queueDate)}</option>)}</select></label></section>{item?<article className="printable-card official-document"><div className="clinic-document-head"><HeartPulse/><div><b>CLARA care</b><span>ClaraCare Clinic · Official document</span></div></div><h2>{type}</h2><p>This is to certify that <b>{name(item.patient)}</b> was seen at ClaraCare Clinic on {new Date(item.queueDate).toLocaleDateString()} under the care of Dr. {item.doctor?.name}.</p>{type==='Consultation Summary'&&<><h4>Initial complaint</h4><p>{item.vitals?.initialComplaint||'Not recorded'}</p><h4>Vital signs</h4><p>Temperature: {item.vitals?.temperature||'—'} °C · Blood pressure: {item.vitals?.bloodPressure||'—'} · Pulse: {item.vitals?.pulse||'—'} bpm · SpO₂: {item.vitals?.oxygenLevel||'—'}%</p></>}{type==='Laboratory Request'&&<p>Requested examination: ______________________________________________</p>}<div className="signature-line">Dr. {item.doctor?.name}<small>{item.doctor?.specialty} · Authorized physician</small></div><button className="primary print-hide" onClick={()=>window.print()}><Printer/> Print document</button></article>:<div className="empty">Choose a completed encounter to prepare a document.</div>}</div>}

export function NotificationsPage(){const{user}=useAuth(),[items,setItems]=useState([]);const load=useCallback(()=>api.get('/notifications').then(r=>setItems(r.data)),[]);useEffect(()=>{load()},[load]);const read=async id=>{await api.patch(`/notifications/${id}/read`);load()};return <div className="page"><PageHead number="12" label="Clinic alerts" title="Notifications" italic="up to date"/><div className="notification-list">{items.map(n=>{const unread=!n.readBy?.includes(user.id);return <article className={unread?'unread':''} key={n._id}><Bell/><div><small>{n.type} · {date(n.createdAt)}</small><h3>{n.title}</h3><p>{n.message}</p></div>{unread&&<button onClick={()=>read(n._id)}>Mark read</button>}</article>})}{!items.length&&<div className="empty">No notifications.</div>}</div></div>}
